fix: exclude EL10+ from dnf_module mysql disable
EL10 (CentOS Stream 10, RHEL 10, AlmaLinux 10, etc.) does not have
a mysql dnf module, so attempting to disable it fails with:

  Unable to resolve argument mysql
  Error: Problems in request:
  missing groups or modules: mysql

This change limits the dnf_module disable to EL8 and EL9 only,
where the module actually exists.

Signed-off-by: Dan Webb <dan.webb@damacus.io>