feat: add EL 10 support and modernize platforms (#75)
* fix: exclude EL10+ from dnf_module mysql disable

EL10 (CentOS Stream 10, RHEL 10, AlmaLinux 10, etc.) does not have
a mysql dnf module, so attempting to disable it fails with:

  Unable to resolve argument mysql
  Error: Problems in request:
  missing groups or modules: mysql

This change limits the dnf_module disable to EL8 and EL9 only,
where the module actually exists.

Signed-off-by: Dan Webb <dan.webb@damacus.io>

* feat: modernize platforms and add EL 10 support

- Remove EOL platforms: centos-7, centos-stream-8, oraclelinux-7

- Remove non-yum platforms: debian-9/10/11/12, ubuntu-18.04/20.04/22.04/23.04

- Add EL 10: almalinux-10, centos-stream-10, rockylinux-10

- Update CI matrix with proper excludes for mysql55/56/57

* fix: exclude EL 10 from resource/connectors suites

MySQL repos don't support EL 10 yet

* fix: support EL 10 by falling back to EL 9 repos

MySQL repos only go up to EL 9, so use EL 9 repos for EL 10+

* fix: exclude Amazon Linux from dnf_module mysql disable

Amazon Linux 2023 doesn't have a mysql dnf module

* fix: update attributes for Amazon Linux 2023 and EL 10

- mysql-connectors-community: use EL 9 repos for AL2023 and EL 10+

- mysql57-community: use EL 7 repos for AL2023

* refactor: remove EOL platform logic

* feat: add MySQL 8.0 and 8.4 support

- Add mysql80-community and mysql84-community attributes

- Add mysql80 and mysql84 recipes

- Update README with new versions and modern examples

- Add mysql80 and mysql84 to CI matrix

* Add mise and rubocop files

Signed-off-by: Dan Webb <dan.webb@damacus.io>

* refactor: remove EOL mysql55/56/57 from CI matrix

* fix: correct MySQL 8.4 repo URL and add dnf_module disable

- Fix mysql-8.4-lts-community to mysql-8.4-community (correct URL)

- Add dnf_module mysql disable to mysql80/84 recipes for EL8/EL9

---------

Signed-off-by: Dan Webb <dan.webb@damacus.io>